const $container= $('#container')
const $h1= $('<h1>Hogwarts</h1>').appendTo('#container')
const $h2= $('<h2>Nicholas Murray</h2>').appendTo('#container')
const $h3= $('<h3>Hufflepuff</h3>').appendTo('#container')
const $h4= $('<h4>Junior</h4>').appendTo('#container')
$h4.addClass("cat")
const $h4wand= $('<h4>Holly Wand with Unicorn Hair Core</h4>').appendTo('#container')

const $ul= $('<ul>').attr('storage','trunk').appendTo('#container')
const $butterBeer= $('<li>Butter Beer</li>').appendTo($ul)
const $invisibilityCloak= $('<li>Invisibility Cloak</li>').appendTo($ul)
$invisibilityCloak.addClass('secret')
const $magicMap= $('<li>Magic Map</li>').appendTo($ul)
$magicMap.addClass('secret')
const $timeTurner= $('<li>TimeTurner</li>').appendTo($ul)
$timeTurner.addClass('secret')
const $leash= $('<li>Leash</li>').appendTo($ul)
$leash.addClass('cat')
const $jellyBeans= $('<li>Bertie Botts Every Flavor [Jelly] Beans</li>').appendTo($ul)
